version: '3.9'

services:
#  app:
#    build: .
#    container_name: notice-me-server
#    ports:
#      - 8080:8080
#    depends_on:
#      mariadb:
#        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#    networks:
#      - notice-me-server
  rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASSWORD}
    ports:
      - ${RABBIT_MQ_PORT}:5672
      - ${RABBIT_MQ_PORT_UI}:15672
    networks:
      - notice-me-server
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
  mariadb:
    image: mariadb:10.7
    restart: always
    container_name: mariadb-notice-me-server
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=notice_me_server
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - notice-me-server
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
volumes:
  dbvolume:

networks:
  notice-me-server:
