server:
  host: 127.0.0.1
  port: 8080
  cors: [localhost]
  env: "dev"
  tlsKey: ""
  tlsCert: ""
db:
  user: root
  pwd: root
  port: 3306
  host: mariadb
  name: notice_me_server
rabbit:
  user: guest
  pwd: guest
  port: 5672
  host: rabbit
  enabled: true
  queues:
    -
      name: notification.notify
      exchange: notification
      durable: true
      autoDelete: false
      exclusive: false
      noWait: false

