server:
  host: localhost
  port: 8090
  cors: ["localhost:3000", "http://localhost:3000", "127.0.0.0:3000", "*"]
  env: "dev"
  tlsKey: ""
  tlsCert: ""
db:
  user: root
  pwd: root
  port: 3306
  host: localhost
  name: notice_me_server
rabbit:
  user: guest
  pwd: guest
  port: 5672
  host: localhost
  consumersCount: 4
  queues:
     -
      name: notification.notify
      exchange: notification
      durable: true
      autoDelete: false
      exclusive: false
      noWait: false
     -
       name: notification.create
       exchange: notification
       durable: true
       autoDelete: false
       exclusive: false
       noWait: false
